apiVersion: v1
kind: Secret
metadata:
  name: banka-app-secrets
  namespace: banka-1
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: enter-your-password
  USER_SERVICE_DB_HOST: db-pgbouncer
  USER_SERVICE_DB_PORT: "5432"
  USER_SERVICE_DB_NAME: user_service
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: enter-your-password
  POSTGRES_HOST: db-pgbouncer
  POSTGRES_PORT: "5432"
  POSTGRES_DB: notification_db
  USER_SERVICE_DB_USER: postgres
  USER_SERVICE_DB_PASSWORD: enter-your-password
  BANKING_CORE_DB_HOST: db-pgbouncer
  BANKING_CORE_DB_PORT: "5432"
  BANKING_CORE_DB_NAME: banking_core
  BANKING_CORE_DB_USER: postgres
  BANKING_CORE_DB_PASSWORD: enter-your-password
  MARKET_SERVICE_DB_HOST: db-pgbouncer
  MARKET_SERVICE_DB_PORT: "5432"
  MARKET_SERVICE_DB_NAME: market_service
  MARKET_SERVICE_DB_USER: postgres
  MARKET_SERVICE_DB_PASSWORD: enter-your-password
  TRADING_DB_HOST: db-pgbouncer
  TRADING_DB_PORT: "5432"
  TRADING_DB_NAME: trading
  TRADING_DB_USER: postgres
  TRADING_DB_PASSWORD: enter-your-password
  CREDIT_DB_HOST: db-pgbouncer
  CREDIT_DB_PORT: "5432"
  CREDIT_DB_NAME: credit_db
  CREDIT_DB_USER: postgres
  CREDIT_DB_PASSWORD: enter-your-password
  INTERBANK_DB_HOST: db-pgbouncer
  INTERBANK_DB_PORT: "5432"
  INTERBANK_DB_NAME: interbank_service
  INTERBANK_DB_USER: postgres
  INTERBANK_DB_PASSWORD: enter-your-password
  SAGA_DB_HOST: db-pgbouncer
  SAGA_DB_PORT: "5432"
  SAGA_DB_NAME: saga_db
  SAGA_DB_USER: postgres
  SAGA_DB_PASSWORD: enter-your-password
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: enter-your-password
  JWT_SECRET: enter-your-key
  INFLUX_ADMIN_USERNAME: enter-your-key
  INFLUX_ADMIN_PASSWORD: enter-your-key
  INFLUX_ADMIN_TOKEN: enter-your-token
  TWELVE_DATA_API_KEY: "enter-your-key"
  ALPHA_VANTAGE_API_KEY: "enter-your-key"
  MAIL_USERNAME: "enter-your-key"
  MAIL_PASSWORD: "enter-your-key"
  FCM_PROJECT_ID: banka-1-firebase
  BANKA2_BASE_URL: http://interbank-service:8091/_mock/banka2/
  BANKA2_INBOUND_TOKEN: enter-your-password
  BANKA2_OUTBOUND_TOKEN: enter-your-password
