apiVersion: v1
kind: Secret
metadata:
  name: banka-analytics-db
  namespace: banka-1
type: Opaque
stringData:
  trading-user: postgres
  trading-password: postgres
  market-user: postgres
  market-password: postgres
