--liquibase formatted sql

--changeset codex:006-create-stock-option
CREATE TABLE stock_option (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker VARCHAR(64) NOT NULL,
    stock_listing_id BIGINT NOT NULL,
    option_type VARCHAR(16) NOT NULL,
    strike_price NUMERIC(19, 4) NOT NULL,
    implied_volatility NUMERIC(19, 8) NOT NULL,
    open_interest INTEGER NOT NULL,
    settlement_date DATE NOT NULL,
    CONSTRAINT uk_stock_option_ticker UNIQUE (ticker),
    CONSTRAINT fk_stock_option_stock_listing
        FOREIGN KEY (stock_listing_id) REFERENCES stock (id)
);

CREATE INDEX idx_stock_option_stock_listing ON stock_option (stock_listing_id);
