package app.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Index;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

/**
 * Persistent delivery tracking record used as the source of truth for retry state.
 */
@Entity
@Table(
        name = "notification_deliveries",
        indexes = {
                @Index(name = "idx_notification_deliveries_status", columnList = "status"),
                @Index(name = "idx_notification_deliveries_next_attempt_at", columnList = "next_attempt_at")
        }
)
@Getter
@Setter
public class NotificationDelivery {
    /**
     * Internal UUID generated by this service; also used by retry queue tasks.
     */
    @Id
    @Column(nullable = false, updatable = false)
    private String deliveryId;

    /**
     * Final email recipient used by SMTP sender.
     */
    @Column(nullable = false)
    private String recipientEmail;

    /**
     * Rendered email subject.
     */
    @Column(nullable = false)
    private String subject;

    /**
     * Rendered email body.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String body;

    /**
     * Current delivery lifecycle status.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationDeliveryStatus status;

    /**
     * Event type resolved from RabbitMQ routing key.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationType notificationType;

    /**
     * Number of failed attempts already performed.
     */
    @Column(nullable = false)
    private int retryCount;

    /**
     * Maximum failed attempts allowed before terminal failure.
     */
    @Column(nullable = false)
    private int maxRetries;

    /**
     * Last error message from SMTP send failure.
     */
    @Column(columnDefinition = "TEXT")
    private String lastError;

    /**
     * Scheduled timestamp for the next retry attempt.
     */
    @Column(name = "next_attempt_at")
    private Instant nextAttemptAt;

    /**
     * Timestamp of the most recent send attempt.
     */
    private Instant lastAttemptAt;

    /**
     * Timestamp when delivery was successfully sent.
     */
    private Instant sentAt;

    /**
     * Entity creation timestamp.
     */
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Entity last update timestamp.
     */
    @Column(nullable = false)
    private Instant updatedAt;

    /**
     * Initializes auditing timestamps before first persistence.
     */
    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        createdAt = now;
        updatedAt = now;
    }

    /**
     * Updates {@link #updatedAt} before each persistence update.
     */
    @PreUpdate
    void onUpdate() {
        updatedAt = Instant.now();
    }
}
